### ISSUE TITLE
Initial Tab

### ISSUE THREAD

**Issue by pndaza** [caduandrade/tabbed_view#12]
is there initialtab for TabContoller like PageView's PageController?.

**Comment by caduandrade** [comment]
Hi @pndaza ! Sorry for the delay in responding, busy week.

You can use the `selectedIndex` in the `initState` before adding any listeners to the controller (just to make sure it doesn't notify something at the wrong time).

Example:

```dart
_controller.selectedIndex = 1;
```

**Comment by pndaza** [comment]
Thanks for great package.
