### ISSUE TITLE
Error: 'MenuThemeData' is imported from both 'package:flutter/src/material/menu_theme.dart' and 'package:tabbed_view/src/theme/menu_theme_data.dart'

### ISSUE THREAD

**Issue by avmakesh** [caduandrade/tabbed_view#15]
If we were using the  **Flutter version 3.4.0-36.0.pre.5 on channel master** and it caused the build error below :

**""flutter-build": Error: 'MenuThemeData' is imported from both 'package:flutter/src/material/menu_theme.dart' and 'package:tabbed_view/src/theme/menu_theme_data.dart'."**

So we revert back the flutter version to stable **(Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git)** , then it's working without any issues. 

So the issue is  once the new code get merged into the stable version we will face the same issue again with **tabbed_view** ?

**Comment by caduandrade** [comment]
Hi @avmakesh ! I will take a look.

**Comment by caduandrade** [comment]
`The name 'MenuThemeData' is defined in the libraries 'package:flutter/src/material/menu_theme.dart (via package:flutter/material.dart)' and 'package:tabbed_view/src/theme/menu_theme_data.dart (via package:tabbed_view/tabbed_view.dart)'. `

The new Flutter version also has a class with the same name.

**Comment by avmakesh** [comment]
> To avoid conflict and having to import using "as", I'm going to rename `MenuThemeData` to `TabbedViewMenuThemeData`.

When we can expect the new version ?

**Comment by caduandrade** [comment]
> When we can expect the new version ?

In the next 122 seconds. :smile:

**Comment by caduandrade** [comment]
@avmakesh, done. Version `1.14.0`. If you have another problem, let me know.

**Comment by avmakesh** [comment]
Sure, Thank you.
