### ISSUE TITLE
MenuThemeData class name clash

### ISSUE THREAD

**Issue by raygray** [caduandrade/tabbed_view#16]
Recently, the Flutter team added **MenuThemeData** class to the material package. This name clashes with your class of the same name.

**Comment by caduandrade** [comment]
Hi @raygray! 

I renamed this class in version 1.14.0, ok? I believe you are not using this version, right?

**Comment by raygray** [comment]
Oh, that was fast. Yes, I totally missed this one. Btw, great library!
