### ISSUE TITLE
Request for assistance

### ISSUE THREAD

**Issue by garthawaters** [caduandrade/tabbed_view#18]
Hi,

Thanks for a great product.

Is it possible to change the name on the Tab programmatically please?
and
Is it possible to have a tap listener on the tab even if it is already selected?

Many Thanks
Garth Waters

**Comment by garthawaters** [comment]
Sorry I saw you have already added the TabbedViewController with the getTabByIndex.
So please ignore above request

Many Thanks
Garth

**Comment by caduandrade** [comment]
No problem. If you need further information, please contact me.

**Comment by garthawaters** [comment]
Thanks very much, your prompt assistance is greatly appreciated. Sent from Mail for Windows From: Carlos Eduardo Leite de AndradeSent: Tuesday, 01 November 2022 18:39To: caduandrade/tabbed_viewCc: garthawaters; State changeSubject: Re: [caduandrade/tabbed_view] Request for assistance (Issue #18) No problem. If you need further information, please contact me.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
