### ISSUE TITLE
Leading Widget on tab

### ISSUE THREAD

**Issue by trhagado** [caduandrade/tabbed_view#22]
Feature Request: Allow an optional prefix icon on tab headers in front of the the tab text and any tab buttons. This feature is available for many desktop widget packages (see example below) and would be very helpful in the tabbed_view widget. 

![image](https://user-images.githubusercontent.com/50645505/210299504-388ee5bb-b133-4652-85cb-47c9b6a49813.png)

**Comment by caduandrade** [comment]
Hi @trhagado ! 

Now you can use a builder:

```dart
    List<TabData> tabs = [
      TabData(
          text: 'Tab 1',
          leading: (context, status) => Icon(Icons.star, size: 16)),
      TabData(text: 'Tab 2'),
      TabData(text: 'Tab 3')
    ];
    TabbedView tabbedView = TabbedView(controller: TabbedViewController(tabs));
```
