### ISSUE TITLE
Ability to close tab which is not in focus / selected

### ISSUE THREAD

**Issue by 5hirish** [caduandrade/tabbed_view#30]
Currently to close a tab, the tab has to be selected and then it can be closed. How can we integrate functionality to close other tabs that are not in focus or selected.

Happy to contribute this if any direction is available.

**Comment by 5hirish** [comment]
Thanks a bunch @caduandrade ! Is there any way to introduce tab reordering functionality?

**Comment by caduandrade** [comment]
Sure, it's on the roadmap
