### ISSUE TITLE
No named parameter with the name 'draggableTabBuilder'

### ISSUE THREAD

**Issue by enwi** [caduandrade/tabbed_view#33]
Since version `1.17.0` I am facing the following issue during build:

```
docking-1.11.0/lib/src/internal/widgets/docking_tabs_widget.dart(91,9): error GC6690633: No named parameter with the name 'draggableTabBuilder'
```

**Comment by caduandrade** [comment]
Fixed by https://github.com/caduandrade/docking_flutter/issues/28
Need to update the `docking` package to 1.11.1
