### ISSUE TITLE
Tab Size

### ISSUE THREAD

**Issue by NickSigoff** [caduandrade/tabbed_view#34]
How can we set a specific tab size so that it does not adjust to the size of the text inside?

**Comment by caduandrade** [comment]
Hi @NickSigoff !

It's not possible. How do you expect the behavior if the text is larger than the defined size? Cut with "..."?

**Comment by NickSigoff** [comment]
Yes exactly

**Comment by caduandrade** [comment]
Done. Version 1.19.0 released. Added `textSize` to the `TabData` class.
