### ISSUE TITLE
Custom decorations for unselected tabs

### ISSUE THREAD

**Issue by Omegaki113r** [caduandrade/tabbed_view#44]
Great project by the way. 

I am using your docking library to develop. I was going through documentation and issues but i didn't found anything that is related to this. 
I am using Tabbed Docking from your library and i want 2 selected tab to look like physical buttons. Selected Tabs looks like it's Pressed and unselected ones will look like they are popping out of the screen. 

![image](https://github.com/caduandrade/tabbed_view/assets/44817852/e7a44fbf-5248-4518-9d8d-01cd37c9ee72)

So the selected behaviour is working as expected. But i don't see any API to set the decoration for the unselected tabs. I want my tabs to look like the buttons (popped out).

Can you let me know whether you have an API for this behaviour i am trying to make?

**Comment by caduandrade** [comment]
Hi @Omegaki113r!

You can change the `TabThemeData` that is inside the `TabbedViewThemeData`.

This class represents the normal state of the tab (not selected).
You can override some attributes for the states (selected, disabled and hover) using the `TabStatusThemeData` that is inside the `TabThemeData`.

As there are a lot of configuration options, it gets a little confusing but here is a simple example I made to change the example committed to the project:

```dart
    TabbedViewThemeData themeData = TabbedViewThemeData.classic();
    themeData.tab
      ..decoration = BoxDecoration(color: Colors.green)
      ..selectedStatus.decoration = BoxDecoration(color: Colors.blue)
      ..highlightedStatus.decoration = BoxDecoration(color: Colors.yellow);

    TabbedView tabbedView = TabbedView(controller: _controller);
    return Scaffold(
        body: Container(
            child: TabbedViewTheme(child: tabbedView, data: themeData),
            padding: EdgeInsets.all(32)));
```

To achieve the same effect you can configure the decoration as you would with `Container` Flutter. You can use a `BoxDecoration`.

You can see more some examples in [https://caduandrade.github.io/tabbed_view](https://caduandrade.github.io/tabbed_view)

**Comment by Omegaki113r** [comment]
> Hi @Omegaki113r!
> 
> You can change the `TabThemeData` that is inside the `TabbedViewThemeData`.
> 
> This class represents the normal state of the tab (not selected). You can override some attributes for the states (selected, disabled and hover) using the `TabStatusThemeData` that is inside the `TabThemeData`.
> 
> As there are a lot of configuration options, it gets a little confusing but here is a simple example I made to change the example committed to the project:
> 
> ```dart
>     TabbedViewThemeData themeData = TabbedViewThemeData.classic();
>     themeData.tab
>       ..decoration = BoxDecoration(color: Colors.green)
>       ..selectedStatus.decoration = BoxDecoration(color: Colors.blue)
>       ..highlightedStatus.decoration = BoxDecoration(color: Colors.yellow);
> 
>     TabbedView tabbedView = TabbedView(controller: _controller);
>     return Scaffold(
>         body: Container(
>             child: TabbedViewTheme(child: tabbedView, data: themeData),
>             padding: EdgeInsets.all(32)));
> ```
> 
> To achieve the same effect you can configure the decoration as you would with `Container` Flutter. You can use a `BoxDecoration`.
> 
> You can see more some examples in https://caduandrade.github.io/tabbed_view

Amazing.. This is what i needed to do.. 

now i get the exact result i wanted.
Thanks for the Quick reply and help 

![image](https://github.com/caduandrade/tabbed_view/assets/44817852/67f5778b-401c-4989-b3b9-c491f77516fe)
